### ISSUE TITLE
Cant Build the NextJS App

### ISSUE THREAD

**Issue by netz-sg** [nuotsu/sanitypress#39]
Fresh pull from the Repo, and i got this Error! 

`[12:46:49.848]  ⨯ ESLint: Error while loading rule '@typescript-eslint/no-empty-function': Cannot read properties of undefined (reading 'allow') Occurred while linting /vercel/path0/src/app/(frontend)/[...slug]/page.tsx
[12:46:57.188]    Collecting page data ...
[12:47:02.850]    Generating static pages (0/11) ...
[12:47:03.768]    Generating static pages (2/11) 
[12:47:03.768]    Generating static pages (5/11) 
[12:47:03.769]    Generating static pages (8/11) 
[12:47:08.802] Error occurred prerendering page "/blog". Read more: https://nextjs.org/docs/messages/prerender-error
[12:47:08.802] Error: Unable to parse value of "$limit=undefined". Please quote string values.
[12:47:08.802]     at onResponse (/vercel/path0/.next/server/chunks/5050.js:5:1066)
[12:47:08.803]     at i (/vercel/path0/.next/server/chunks/5050.js:2:2865)
[12:47:08.803]     at /vercel/path0/.next/server/chunks/5050.js:2:3064
[12:47:08.803]     at /vercel/path0/.next/server/chunks/5050.js:2:3173
[12:47:08.803]     at /vercel/path0/.next/server/chunks/5050.js:2:1400
[12:47:08.803]     at u.onreadystatechange (/vercel/path0/.next/server/chunks/5050.js:2:1603)
[12:47:08.803]     at /vercel/path0/.next/server/chunks/5050.js:2:237
[12:47:08.803]     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[12:47:08.803] Export encountered an error on /(frontend)/[...slug]/page: /blog, exiting the build.
[12:47:08.809]  ⨯ Static worker exited with code: 1 and signal: null
[12:47:08.874] Error: Command "npm run build" exited with 1
[12:47:09.367] `

i cant deploy it on vercel ore Coolify... with npm run dev it works but the deploy don't work :/

**Comment by Brettkgamble** [comment]
Also had a similar issue.  Unable to build on Vercel.  Seems to be  issue with Suspense boundary and useSearchParams in the navigation.tsx file (guessing).  I deleted the Next and Sanity directories and did a full install using Yarn.   Everything seems to work in Dev.

------------------------------

[08:03:48.750]    ▲ Next.js 15.0.3
[08:03:48.750] 
[08:03:48.793]    Creating an optimized production build ...
[08:05:30.849]  ✓ Compiled successfully
[08:05:30.856]    Linting and checking validity of types ...
[08:05:33.026] 
[08:05:33.027]  ⚠ The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/app/building-your-application/configuring/eslint#migrating-existing-config
[08:05:33.411]  ⨯ ESLint: Error while loading rule '@typescript-eslint/no-empty-function': Cannot read properties of undefined (reading 'allow') Occurred while linting /vercel/path0/src/app/(frontend)/[...slug]/page.tsx
[08:05:41.064]    Collecting page data ...
[08:05:47.483]    Generating static pages (0/21) ...
[08:05:48.331]    Generating static pages (5/21) 
[08:05:52.522]    Generating static pages (10/21) 
[08:05:52.523]  ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
[08:05:52.523]     at u (/vercel/path0/.next/server/chunks/8481.js:1:1508)
[08:05:52.523]     at l (/vercel/path0/.next/server/chunks/8481.js:1:3980)
[08:05:52.523]     at Object.useAdapter (/vercel/path0/.next/server/chunks/2875.js:1:77175)
[08:05:52.523]     at c (/vercel/path0/.next/server/chunks/2875.js:2:770)
[08:05:52.523]     at f (/vercel/path0/.next/server/chunks/2875.js:2:3135)
[08:05:52.523]     at r (/vercel/path0/.next/server/chunks/9410.js:1:12007)
[08:05:52.523]     at w (/vercel/path0/.next/server/chunks/9410.js:1:11628)
[08:05:52.523]     at N (/vercel/path0/.next/server/chunks/9410.js:1:11410)
[08:05:52.523]     at n$ (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:45906)
[08:05:52.523]     at nI (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:47681)
[08:05:52.523] Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
[08:05:52.523] Export encountered an error on /(frontend)/page: /, exiting the build.
[08:05:52.529]  ⨯ Static worker exited with code: 1 and signal: null
[08:05:52.600] Error: Command "npm run build" exited with 1
[08:05:53.322]

**Comment by mitchuman** [comment]
Thanks @netz-sg and @Brettkgamble for reporting. I've released [a new fix on v5.3.2](https://github.com/nuotsu/sanitypress/commit/63b738bb2efcfed97c7f3178067fd95a7abc3959).

There's 3 files you'll need to make super minor edits to which should resolve the issue. Let me know if that worked!

**Comment by Brettkgamble** [comment]
Made the changes, runs on Dev, built on Vercel.  Thanks @nuotsu  for the very fast fix!
